# Generated by Django 4.0 on 2021-12-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=20)),
                ('classe', models.CharField(max_length=20)),
                ('sexe', models.CharField(max_length=1)),
                ('filleul', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Filleul', to='parrain.etudiant')),
                ('parrain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parrain.etudiant')),
            ],
        ),
    ]
