# Generated by Django 4.0 on 2022-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatParrain', models.CharField(max_length=30)),
                ('MatFilleul', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='filleul',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='parrain',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
