# Generated by Django 4.0 on 2022-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrain', '0002_parrainage_remove_etudiant_filleul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrainage',
            name='MatFilleul',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parrainage',
            name='MatParrain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
