# Generated by Django 4.0 on 2021-12-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parrain', '0002_alter_etudiant_filleul_alter_etudiant_parrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='filleul',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='parrain',
        ),
    ]
