# Generated by Django 4.0 on 2021-12-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parrain', '0003_remove_etudiant_filleul_remove_etudiant_parrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='filleul',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Filleul', to='parrain.etudiant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='parrain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parrain.etudiant'),
            preserve_default=False,
        ),
    ]
