# Generated by Django 4.0 on 2022-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrain', '0004_remove_etudiant_photo_etudiant_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='num',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
