# Generated by Django 4.0 on 2021-12-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parrain', '0005_alter_etudiant_filleul_alter_etudiant_parrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='filleul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Filleul', to='parrain.etudiant'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parrain.etudiant'),
        ),
    ]
